#!/bin/bash
echo "==== Build Status Check ===="
echo ""
echo "Current Step:"
grep -E "^Step [0-9]" compile.log 2>/dev/null | tail -1 || echo "Not started"
echo ""
echo "Completed Components:"
[ -d "3rdParty/install/boost/lib" ] && echo "✓ Boost installed" || echo "✗ Boost not installed"
[ -d "3rdParty/install/qt/lib" ] && echo "✓ Qt installed" || echo "✗ Qt not installed"
[ -d "3rdParty/install/llvm/lib" ] && echo "✓ LLVM installed" || echo "✗ LLVM not installed"
[ -f "Sourcetrail/build/Release/app/Sourcetrail" ] && echo "✓ Sourcetrail built" || echo "✗ Sourcetrail not built"
echo ""
echo "Disk Usage:"
du -sh 3rdParty/ 2>/dev/null || echo "No 3rdParty directory yet"
echo ""
echo "Last few log lines:"
tail -5 compile.log 2>/dev/null || echo "No log file yet"
